# -*- coding: utf-8 -*-
"""AI .Bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9pQmc0hGV42yGAVaila60z0I-xgpaAt
"""

!pip install -q -U \
    streamlit \
    transformers \
    accelerate \
    sentence-transformers \
    faiss-cpu \
    langchain \
    langchain-community \
    langchain-huggingface \
    unstructured \
    beautifulsoup4 \
    requests \
    pyngrok

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

print("Loading tokenizer...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("Loading model...")

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype="auto",
    device_map="auto"
)

print("Qwen model loaded successfully!")

print("Device:", model.device)

# Commented out IPython magic to ensure Python compatibility.
#  %%writefile app.py

import os
import pickle

import streamlit as st
import torch

from transformers import AutoTokenizer, AutoModelForCausalLM

from langchain_community.document_loaders import UnstructuredURLLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="RockyBot - News Research Tool",
    page_icon="📈",
    layout="wide"
)


# ============================================================
# TITLE
# ============================================================

st.title("RockyBot: News Research Tool 📈")

st.write(
    "Find, Analyze, Understand"
)


# ============================================================
# MODEL CONFIGURATION
# ============================================================

MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

FILE_PATH = "faiss_store.pkl"


# ============================================================
# LOAD QWEN MODEL
# ============================================================

@st.cache_resource
def load_qwen():

    st.write("Loading Qwen model...")

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME
    )

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype="auto",
        device_map="auto"
    )

    return tokenizer, model


tokenizer, model = load_qwen()


# ============================================================
# LOAD EMBEDDING MODEL
# ============================================================

@st.cache_resource
def load_embeddings():

    embeddings = HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL
    )

    return embeddings


embeddings = load_embeddings()


# ============================================================
# QWEN RESPONSE FUNCTION
# ============================================================

def generate_response(prompt, max_new_tokens=400):

    messages = [
        {
            "role": "system",
            "content": (
                "You are a helpful news research assistant. "
                "Answer the user's question using only the "
                "provided article context. "
                "If the context does not contain the answer, "
                "say that the information is not available "
                "in the provided articles."
            )
        },
        {
            "role": "user",
            "content": prompt
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        [text],
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():

        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.3,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(
        outputs[0][inputs.input_ids.shape[1]:],
        skip_special_tokens=True
    )

    return response.strip()


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("News Article URLs")

urls = []

for i in range(3):

    url = st.sidebar.text_input(
        f"URL {i + 1}"
    )

    if url.strip():
        urls.append(url.strip())


process_url_clicked = st.sidebar.button(
    "Process URLs"
)


# ============================================================
# MAIN PLACEHOLDER
# ============================================================

main_placeholder = st.empty()


# ============================================================
# PROCESS URLs
# ============================================================

if process_url_clicked:

    if not urls:

        st.error(
            "Please enter at least one URL."
        )

    else:

        try:

            # ------------------------------------------------
            # LOAD DATA
            # ------------------------------------------------

            main_placeholder.text(
                "Data Loading... Started... ✅"
            )

            loader = UnstructuredURLLoader(
                urls=urls
            )

            data = loader.load()

            if not data:

                st.error(
                    "Could not extract content from the URLs."
                )

                st.stop()


            # ------------------------------------------------
            # SPLIT DATA
            # ------------------------------------------------

            main_placeholder.text(
                "Splitting article text... ✅"
            )

            text_splitter = RecursiveCharacterTextSplitter(
                separators=[
                    "\n\n",
                    "\n",
                    ".",
                    ","
                ],
                chunk_size=1000,
                chunk_overlap=100
            )

            docs = text_splitter.split_documents(
                data
            )


            # ------------------------------------------------
            # CREATE FAISS VECTOR STORE
            # ------------------------------------------------

            main_placeholder.text(
                "Creating embeddings and FAISS index... ✅"
            )

            vectorstore = FAISS.from_documents(
                docs,
                embeddings
            )


            # ------------------------------------------------
            # SAVE VECTOR STORE
            # ------------------------------------------------

            with open(
                FILE_PATH,
                "wb"
            ) as f:

                pickle.dump(
                    vectorstore,
                    f
                )


            main_placeholder.text(
                "Processing completed successfully! ✅"
            )

            st.success(
                f"Processed {len(docs)} text chunks."
            )


        except Exception as e:

            st.error(
                f"Error while processing URLs:\n\n{e}"
            )


# ============================================================
# QUESTION
# ============================================================

query = st.text_input(
    "Question:"
)


# ============================================================
# ANSWER QUESTION
# ============================================================

if query:

    if not os.path.exists(FILE_PATH):

        st.warning(
            "Please process the URLs first."
        )

    else:

        try:

            # ------------------------------------------------
            # LOAD FAISS
            # ------------------------------------------------

            with open(
                FILE_PATH,
                "rb"
            ) as f:

                vectorstore = pickle.load(f)


            # ------------------------------------------------
            # RETRIEVE RELEVANT DOCUMENTS
            # ------------------------------------------------

            relevant_docs = vectorstore.similarity_search(
                query,
                k=4
            )


            # ------------------------------------------------
            # CREATE CONTEXT
            # ------------------------------------------------

            context_parts = []

            for i, doc in enumerate(
                relevant_docs
            ):

                context_parts.append(
                    f"""
ARTICLE {i + 1}

SOURCE:
{doc.metadata.get("source", "Unknown")}

CONTENT:
{doc.page_content}
"""
                )


            context = "\n\n".join(
                context_parts
            )


            # ------------------------------------------------
            # CREATE PROMPT
            # ------------------------------------------------

            prompt = f"""
Use the following news article excerpts to answer
the question.

---------------- CONTEXT ----------------

{context}

-------------- END CONTEXT --------------

QUESTION:

{query}

Answer clearly and concisely.
Mention the source URLs used for the answer.
"""


            # ------------------------------------------------
            # GENERATE ANSWER USING QWEN
            # ------------------------------------------------

            with st.spinner(
                "Qwen is generating the answer..."
            ):

                answer = generate_response(
                    prompt
                )


            # ------------------------------------------------
            # DISPLAY ANSWER
            # ------------------------------------------------

            st.header(
                "Answer"
            )

            st.write(
                answer
            )


            # ------------------------------------------------
            # DISPLAY SOURCES
            # ------------------------------------------------

            st.subheader(
                "Sources"
            )

            sources = set()

            for doc in relevant_docs:

                source = doc.metadata.get(
                    "source"
                )

                if source:
                    sources.add(source)


            for source in sources:

                st.write(
                    source
                )


        except Exception as e:

            st.error(
                f"Error while answering question:\n\n{e}"
            )

!streamlit run app.py --server.port 8501 &>/content/logs.txt &

from google.colab import userdata
userdata.get('NGROK_AUTHTOKEN')

from google.colab import drive
drive.mount('/content/drive')

from google.colab import userdata
from pyngrok import ngrok

token = userdata.get("NGROK_AUTHTOKEN")

ngrok.set_auth_token(token)

public_url = ngrok.connect(8501)

print(public_url)